### ISSUE TITLE
Не работает раздел "Контакты"

### ISSUE THREAD

**Issue by thepetrfreys** [NikitaShal/MkeiitWPTheme#1]
При использовании сайта с мобильного телефона не открывается раздел "Контакты".
Google Pixel, Android 9, Chrome 71

**Comment by thepetrfreys** [comment]
Причем, данная проблема наблюдается не только с мобильного устройства. Windows 10, Firefox 64.0.2

**Comment by NikitaShal** [comment]
> Причем, данная проблема наблюдается не только с мобильного устройства. Windows 10, Firefox 64.0.2

Это должен настроить администратор через админку wordpress, но ему лень, поэтому не открывается 😞

**Comment by NikitaShal** [comment]
Ссылка добавлена, все работает
